const { generateWithGemini } = require("../../shared/gemini");
const { sanitizeText } = require("../../shared/sanitize");
const {
  ttsProvider,
  elevenLabsApiKey,
  elevenLabsBaseUrl,
  elevenLabsModel,
  elevenLabsVoiceEn,
  elevenLabsVoiceSw
} = require("../../config/env");

function getElevenLabsVoiceId(language) {
  return language === "sw" ? elevenLabsVoiceSw : elevenLabsVoiceEn;
}

async function synthesizeWithElevenLabs({ text, language }) {
  if (!elevenLabsApiKey) return null;

  const voiceId = getElevenLabsVoiceId(language);
  const endpoint = `${String(elevenLabsBaseUrl).replace(/\/+$/, "")}/text-to-speech/${voiceId}`;

  const response = await fetch(endpoint, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Accept: "audio/mpeg",
      "xi-api-key": elevenLabsApiKey
    },
    body: JSON.stringify({
      text,
      model_id: elevenLabsModel,
      voice_settings: {
        stability: 0.45,
        similarity_boost: 0.82,
        style: 0.2,
        use_speaker_boost: true
      }
    })
  });

  if (!response.ok) {
    return null;
  }

  const arrayBuffer = await response.arrayBuffer();
  const buffer = Buffer.from(arrayBuffer);
  if (!buffer.length) {
    return null;
  }

  return {
    audioBase64: buffer.toString("base64"),
    audioMimeType: "audio/mpeg",
    ttsVoice: voiceId,
    ttsProvider: "elevenlabs"
  };
}

async function handleVoiceRequest({ language, transcript, provider }) {
  const safeTranscript = sanitizeText(transcript, 500);
  const voiceByLanguage = {
    en: "en-KE-Neural2-A",
    sw: "sw-KE-Standard-A"
  };

  const fallbackReply =
    language === "sw"
      ? "Nimekupata. Nisaidie route, tarehe, na bajeti ili nikupatie chaguo bora."
      : "Got you. Share route, date, and budget so I can suggest the best option.";

  const prompt = [
    "You are a bilingual transport booking voice assistant for Safari Connect.",
    `Language: ${language}.`,
    "Reply in one concise sentence suitable for TTS playback.",
    "Do not claim real-time prices or availability you do not have.",
    "If details are missing, ask for route, date/time, and budget.",
    `User transcript: ${safeTranscript}`
  ].join("\n");

  const generation = await generateWithGemini({ prompt });
  const replyText = generation.text || fallbackReply;

  let audio = null;
  if (ttsProvider === "elevenlabs") {
    audio = await synthesizeWithElevenLabs({ text: replyText, language });
  }

  return {
    language,
    provider,
    transcript: safeTranscript,
    replyText,
    source: generation.source,
    modelUsed: generation.modelUsed,
    disclaimer:
      generation.source === "fallback"
        ? "Voice response used deterministic fallback guidance."
        : "Voice response generated by Gemini from provided context.",
    inputMode: "voice",
    outputMode: audio ? "text-and-audio" : "text-and-tts",
    ttsVoice: audio?.ttsVoice || voiceByLanguage[language] || voiceByLanguage.en,
    ttsProvider: audio?.ttsProvider || "browser",
    audioBase64: audio?.audioBase64 || null,
    audioMimeType: audio?.audioMimeType || null,
    note: audio
      ? "Audio generated by premium TTS provider."
      : "Premium TTS not configured; frontend can use browser speech fallback."
  };
}

module.exports = {
  handleVoiceRequest
};
